keys:
  - &primary age1yubikey1qfeuzecefcjwjnyup4699fs6nwnz2tl3ymlaad5pxj9kflhc852r7j9e3sa
  - &pi age12x08qp6qx2pmm5jhc6658mpwrt88c0mr06dxermvja5dux40fglqmeywhn

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
    - age:
      - *primary
      - *pi