keys:
  - &primary age1yubikey1qfeuzecefcjwjnyup4699fs6nwnz2tl3ymlaad5pxj9kflhc852r7j9e3sa
  - &pi age1vrpuw4qa6fu6ze7qfpj4kd8zsmkuy9ucewd0emcf0rcjt6n7dd9srh8emn

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
    - age:
      - *primary
      - *pi