name: Build NixOS SD Image

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-sd-image:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: dawidde-nixos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true

      - name: Build SD image
        run: |
          nix-build \
            -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-25.11.tar.gz \
            '<nixpkgs/nixos>' \
            -A config.system.build.sdImage \
            -I nixos-config=./pi/sd-image.nix

      - name: Push closure to Cachix
        if: github.event_name != 'pull_request'
        run: |
          nix path-info -r ./result | cachix push dawidde-nixos

      - name: Collect image
        run: |
          mkdir -p artifacts
          find result -type f -name "*.img*" -exec cp {} artifacts/ \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-sd-image
          path: artifacts/