gerbil:
    start_port: ENC[AES256_GCM,data:cXJvUmI=,iv:X+g+WJ1CrHFPuFzRQS7BQA5hikdL5d3qWDDa0YgHP/4=,tag:icJ4fc2x8OdGi+v902q1kw==,type:int]
    base_endpoint: ENC[AES256_GCM,data:FLanRNv3APURAUBsgJOX+LZ+ZA==,iv:QP+d9Y7xBNifCp3Z1Lu4oMcmnFx06q1t76HIAnxD25o=,tag:AdY5oW3kDH0JVR4kGQcnKg==,type:str]
app:
    dashboard_url: ENC[AES256_GCM,data:2XsUWKMb/rG55OPGU6wcsScbwnWJeUjZQqpu,iv:4kmx81zU/H+WFz2bf+TlpdlscBrQPaBs5UAu9teH1WA=,tag:g03ntt9WGJb8UK8wMaCbQA==,type:str]
    log_level: ENC[AES256_GCM,data:ISUdpg==,iv:S7QuFqg/0T8JqDNJdjQkKSf8YyACxseGrwfTkpkgvuQ=,tag:gATjgDBV/YBtgornL2jXlQ==,type:str]
    telemetry:
        anonymous_usage: ENC[AES256_GCM,data:mhxYz48=,iv:Oy25WF98HrII2dJSaM8nRi8PBZ8svy2F5oapRI8VoYU=,tag:H4BFpxvBgr5tLRElL4NS5g==,type:bool]
domains:
    domain1:
        base_domain: ENC[AES256_GCM,data:c7mLy0iN/jXP/Q==,iv:xMOEv0/JRfAVAe+6Edr6Or7XIMC6TTICtOeokYVnNuY=,tag:kbS6sobjuFnkDQFFvzgCWQ==,type:str]
server:
    secret: ENC[AES256_GCM,data:QNEJM4t7TPF1HR26XKXA7p1TsQbg3aScmEughLjErl1sCIFynYqT+m6qbBgzMYmI97fGrpk1bu8U1CpZPvWAWg==,iv:62OdZ3ld8nFhLKxJpMSDtC8dQez/UnRGypA2EOe5sjY=,tag:UTthczRTHUOUmu4vnZ4tDg==,type:str]
    cors:
        origins:
            - ENC[AES256_GCM,data:FiXlKHQOjn4TyigIVIHebpx8oBd0MqgpAUnw,iv:ZOSNgg2M2Ams+mqQPHsFTsqByGrgAkyr2hH9tGHWQTc=,tag:I84jBLCAoOHnjAWWZ/Hz0w==,type:str]
        methods:
            - ENC[AES256_GCM,data:Bu67,iv:3Oz+Paxo5Yz/eQS9AxNS+GdyIXVbfnnCDmmkB1G+adk=,tag:6SHTV8lENiH7qkTxRLLsZw==,type:str]
            - ENC[AES256_GCM,data:w2shLw==,iv:HOfyiSbHxx035aiKZc8YSvkWNey2jVGBygy6OnH/h8I=,tag:TxCQhOoSPQA6gvigu4UoNg==,type:str]
            - ENC[AES256_GCM,data:dSPI,iv:AG7sKv/rqdkPVYGXFLMyBZ4JqC/ieQNCjueGuzATVy4=,tag:ZnyzFTV+pbM6q9K/7NoWYg==,type:str]
            - ENC[AES256_GCM,data:zYG0F9NQ,iv:LM6a2Fw4ozC/E5MIBSQOE9ciJ2zjS6OV5EP7KlWLCMU=,tag:7b45Gpw9fq6JhpuiMiZ6Qw==,type:str]
            - ENC[AES256_GCM,data:/GacmmA=,iv:buzK+4JVsAtITjtSWL/LBpsW0jfyt2KmqUOe/loL8Ds=,tag:uSFv4JLXaQjAYyoJqcVYeg==,type:str]
        allowed_headers:
            - ENC[AES256_GCM,data:ccqgOaczPax1Nrud,iv:eV6Z2D1EflpOnrvvXZEvh785ab36L3qcALR4nLpidns=,tag:at/B/engxUbG+O/YzHGPnQ==,type:str]
            - ENC[AES256_GCM,data:W2P79P0yn/3m2TGk,iv:pi2umxFe+0uVLNawBS9JRAxtCQO+/hWkLNFYJJn8wL8=,tag:ouzEByAJqtDN4+uGZVaLSg==,type:str]
        credentials: ENC[AES256_GCM,data:F5k6nGA=,iv:2Qup2Z5sLuo7NHKwKN0Dm/Y/lLC/2/bIptm1Qes7NeM=,tag:kuMeQF/3UBFVgItePdhLKQ==,type:bool]
flags:
    require_email_verification: ENC[AES256_GCM,data:aVUn4B0=,iv:C/T1SsuN9/oTxpbv8S2dTKx0i77wPldiyUJQBkHsR5s=,tag:ljgzezrEqdxwXd8GmMP9uQ==,type:bool]
    disable_signup_without_invite: ENC[AES256_GCM,data:2NYSrg==,iv:R03yrhpk2EK8FFrnAUkKwFIDzKUFQ3hhErJLS/Zu3Ck=,tag:ct+yCpgmA3Tnm7d1v5NirA==,type:bool]
    disable_user_create_org: ENC[AES256_GCM,data:D1l9r10=,iv:H7rQhTd35D3IvZrvuRz1DfvX2Smbe5Y+fV5T0kJSN30=,tag:vvh109pFK1mDHv+yeGWk7w==,type:bool]
    allow_raw_resources: ENC[AES256_GCM,data:42qHUA==,iv:1m+1PgfZjhtwrlFDQ0kVX3CmOTs8/eURP30qWtC+owM=,tag:kcROWMWWydDs/RRR5knTbw==,type:bool]
email:
    smtp_host: ENC[AES256_GCM,data:buBNxUyrgv6vv3aSbpqzrA==,iv:/hMh6hNiBpa0dpC0hNMbv0ICgwa4jbnL+5oGidlPHRY=,tag:1gNK9qPdmGMBxttOwdJ9kg==,type:str]
    smtp_port: ENC[AES256_GCM,data:PRhM,iv:wr3MzMXWBJZZAUHT/wlVP7NXWkAQ/DiypQwx4csVAQY=,tag:rdMdbmKoI8hf1J4MvEX2Xg==,type:int]
    smtp_user: ENC[AES256_GCM,data:pLI3+zD+8Bs2,iv:w6yTCr2sosl/t33ixFC0o9u/T8yERS26vG9IoksNyhg=,tag:GxHiPWb3XpygnxuiX35eog==,type:str]
    smtp_pass: ENC[AES256_GCM,data:SrG+WiQvlw5vlE/kmw==,iv:bvG2vRiJgX0CPgBRQTfaTX3liJPJjb5WviuIIhfD42U=,tag:SrRz7CNOncJf/aDQtB8qIg==,type:str]
    no_reply: ENC[AES256_GCM,data:TsuN8vR02rcgYOBZorFy+w5WaQ==,iv:sZf4GB68lmwfPSGzfLOrzX9HpOA2mWwI2JrRbeDVPB8=,tag:jeMRkIcCdpEbytrSqu1Y4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEN2U0tvZyBBdXAzQlNH
            dTlkd2dsOXpab3pFY2ZmdW10TVJCb2FydEQxQjY0L3lGOWdhRQp0Vlh0Y21rZTV4
            enVlaUk0UVVDUjkzdTFEU0xreUFUR0QrTVVPNzJFNVI0Ci0tLSBLbWsyL0RZNGFG
            YWw4NTF5MlEwWjBWcnRSSDVObmZlU3czc0ZlQXNqcFJFCtU2kBPth6TpG9Bk8aXA
            jpPxtrxwvGAmxodE4Z3ebfa88THh6lyYYMdTSWFyiOZrCA8k0h6EPZViiLDjT5HZ
            CcE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfeuzecefcjwjnyup4699fs6nwnz2tl3ymlaad5pxj9kflhc852r7j9e3sa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeVBSSFNrL0o3aDZibFNY
            eXVCeFBoVjBEcjdQRWptbElaSHhDKzI5d2owClI3Skc4ZFQ1SnpUVWxWbVRINzZ4
            VXgyQyt6d3FCSHczOFNwMERGd2poY28KLS0tIGJXWHV0TmxTZ0dNR09weDlGTEZJ
            NzZvbU1jRGJpV21oQUNYRlBsV3IwV0kKiBZl5X8QJ3QZG5qga4Yz7kgQ0i8U4iqC
            Vzg2s/thwxL0gwQtliMqQQhfv/IliFcc5yNO5xNBjW3fv7CF572XRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x08qp6qx2pmm5jhc6658mpwrt88c0mr06dxermvja5dux40fglqmeywhn
    lastmodified: "2026-10-03T11:06:48Z"
    mac: ENC[AES256_GCM,data:DQqHhuPfsgrNLPohsYa99uu/iQYKQ6SaTH+f3MUHCchJGmfiv4Ut6M6H99XioPAgppTrkYFAPeEJq/lXNdRec73hlasAMiJYJ7/aFS/AjWsgCVcNMducb6eOW7RLJdQchc9uZKteFnrFpeml8no0xNO9hJIlf2bjokezBZHGgVY=,iv:Hi66xQYpp/tMNiyIDXqzC+NSuduNweGgm30SUrYyIJs=,tag:rcVp8ohX3NqBVGqZgXhNwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
