api:
    insecure: ENC[AES256_GCM,data:ce49gQ==,iv:pfwZVMpg7E7tbasJipwBurH48OQiNt20gBi2bdKqJPc=,tag:Uwxe7hCIImYsRqXReKkuqw==,type:bool]
    dashboard: ENC[AES256_GCM,data:F1X4ig==,iv:M32UdDRJCSdxg4xnNtdBte0md+PJJya6qEIU5s+e0R0=,tag:uA5CkgssqxarDDf5gadwQg==,type:bool]
providers:
    http:
        endpoint: ENC[AES256_GCM,data:DldE59j+K//Jrnsne56/xnREy5PoPq6vQS8kF9Jll670eGXDQNOCnc4k,iv:NQq4nMsovAYjg6itfY277hJY5rkRAwIiu44lHJ4PfP0=,tag:SMLBd3PkdTsZmOjESaj76w==,type:str]
        pollInterval: ENC[AES256_GCM,data:hq0=,iv:dsTUDt02wevZcYLUdevTX5gHo3A/QGvr/+nJ+8ptST4=,tag:DVRclcirJ/dZIcibdse2iQ==,type:str]
    file:
        filename: ENC[AES256_GCM,data:KZoaGelzdgAFyyMeuJ9Oh+KbQFTK4YY8X595c/FYaA==,iv:o7OL7cuVUk5tOT4mklBBOMJ/WxueWzoQxe1IIAMuIow=,tag:0gtTOuSc+LFj3rj61rWuAg==,type:str]
experimental:
    plugins:
        badger:
            moduleName: ENC[AES256_GCM,data:7ImfeYSslTp1NcMmhVn++CI0FS75KNs=,iv:/kcHBgNv5SY1FjkCXDvT7HNlG3ET7k8jVxL/xXsIuag=,tag:I175hdk5a55X4n+jzddoeQ==,type:str]
            version: ENC[AES256_GCM,data:cGWp6I2g,iv:sRh2xHwQtxsTAl1+X4aPrfy0uscf0WbLAIdFI8MlJ+w=,tag:MQcdN2f3JwOYw/8aZkne9A==,type:str]
log:
    level: ENC[AES256_GCM,data:TOvDYg==,iv:efLPNPnuqEXoVxgET78fHMht6JRm12aPiZHZrWbBF3o=,tag:V4B0fZs03vNMjKj0UXeZNQ==,type:str]
    format: ENC[AES256_GCM,data:JGSswTnP,iv:5HSw2SfwNAOZ6ewj10ueUzMwzjDSH+nB0w1ZtmpWdGM=,tag:5ng03qkflwGpjnC5qd7Zjw==,type:str]
    maxSize: ENC[AES256_GCM,data:lvNd,iv:e5bZC7Z5Qn5lS7J9KnmH0gn/qA+43iyQ92ciKSrTqt8=,tag:8gHwtO7wPFtxTdjuSs8/rg==,type:int]
    maxBackups: ENC[AES256_GCM,data:TQ==,iv:nqYeT/zEATYcoEaS6lwdH2u90n1P+/DiIhyazChozvk=,tag:2D0oE/A6SG+Gy/u1sbxUig==,type:int]
    maxAge: ENC[AES256_GCM,data:hA==,iv:nJyXz8xsXyIdoy3efmDqLc+q6malX250cISzBcu1mtQ=,tag:Vuy2H2xguWRQUju10xvQAQ==,type:int]
    compress: ENC[AES256_GCM,data:mpO+XQ==,iv:BM7BPoGqfoh27hcQGZ9O2wz4f15ksdXO9EeogBOWN1Y=,tag:MfdSxycw4yrluVK1bz/OdA==,type:bool]
certificatesResolvers:
    letsencrypt:
        acme:
            httpChallenge:
                entryPoint: ENC[AES256_GCM,data:P0xG,iv:8+duTHGb2LA6XeRp8rQ+q5Uwu7fxWT+6hxmMlQgKjRA=,tag:zWqXUC4cMQs3Dm4RLpx4Eg==,type:str]
            email: ENC[AES256_GCM,data:v1Cwhx1CzloMY/cNxOy097NC,iv:tVOt7f2lEIdUcTSkAQY6MYvtg9K0Um06a12x58pNk00=,tag:wUlRpNp5gtZGsCuQFEn3Cw==,type:str]
            storage: ENC[AES256_GCM,data:dGzW2ynG2vBcllGCYBWIT3hQsSf6Yg==,iv:6GRWc8gbeDDUtubwk7OgFOR1KXmhZZrWk9oMbC3kjZE=,tag:TF7CVDFiDSn1ZgjlYhcs1w==,type:str]
            caServer: ENC[AES256_GCM,data:J3CsMH6Y7DjtC6S4RvqHwMqIcIg2cUsLN9s/X+EycOqK4Z7t/YWR80hi4tgLrg==,iv:w4W8nPLrq5Kj53JeqKMAmW996X7tMv85axBG69Unky0=,tag:up2IvwGuQiHbqlktI363Tw==,type:str]
entryPoints:
    web:
        address: ENC[AES256_GCM,data:Qkoh,iv:oXE0/I2Wf1af8j39NFbG/bavG/8IGUnw6x6WpLfZlJY=,tag:yJR1wFfE+q5BNnPzmNKk8w==,type:str]
    websecure:
        address: ENC[AES256_GCM,data:/+KS1g==,iv:NyTLt04UjpKK0w2IxmK0ex88UZRTj3Cy1Y9jzxAIT2g=,tag:VPUn+rrbkORmcJjKfuds7A==,type:str]
        transport:
            respondingTimeouts:
                readTimeout: ENC[AES256_GCM,data:JfFk,iv:72wSmYnefTFITPX/ZHGoYKeuceJyIJ91NAL7qJb8dNY=,tag:F8Y+xcdplxzMPN56uXB27w==,type:str]
        http:
            tls:
                certResolver: ENC[AES256_GCM,data:cmF7pgbAGPa8CK0=,iv:FK9pbI3CgFagmDnXs1akdTBIIK/q7q/PK74NZo4G4II=,tag:U7BcmsENuxUgTuvIlpTo4A==,type:str]
            encodedCharacters:
                allowEncodedSlash: ENC[AES256_GCM,data:SkhAUw==,iv:NYs1wExtwh2yEdLBaGTj/xgc3wFpJDw0qhT/XgSBKxc=,tag:H8MCHi3f7gl5P/YgCkbTZA==,type:bool]
                allowEncodedQuestionMark: ENC[AES256_GCM,data:Cn8EdQ==,iv:tchDgOMPpUCbjq9DyLFlR0Yxtge/bkgntsUaqYYh1oA=,tag:I1QxOKOHfhEir6jFGddx+A==,type:bool]
serversTransport:
    insecureSkipVerify: ENC[AES256_GCM,data:Mclfkg==,iv:4HAxJOeydaSDPAvZA+jhCUMpmY1Gu9CdV+pf7Xo8FGY=,tag:OHES945jtmtV2DB8my8E0A==,type:bool]
ping:
    entryPoint: ENC[AES256_GCM,data:+Dw7,iv:Ly/PXQHQQ5AXSmyto7MqpVRkQ7B8ndPfEqf9V02K60E=,tag:fI56Tw8L0rITq6LoDpkcEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEN2U0tvZyBBemVmbXFX
            Ni8wRUdaa3dKOEQvQmJKWjVjV280ZG5JajkxeEV2VG4xa3p3cApOTXc0N1czZ3VY
            cCt4dUM4TzVXYWJ6RWVqSkZlZ015M3VxbTlGaXE2cEhRCi0tLSBnV3NxZWExRlNK
            OFFBK25MYzh4ZHJPMkVMVUsxZmRHRGhhOXhDU1pIYmE4Cm4r1aaA7ULJUJjrFtAp
            gjCT+Ky05qQ+cnWdyMHJYi6/2WhCX3RkKX2UyCWsysJioMRAsBXqAQyU1lWgxFhA
            Qb8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfeuzecefcjwjnyup4699fs6nwnz2tl3ymlaad5pxj9kflhc852r7j9e3sa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYStCQnV6ZUlySnBWZWtm
            RkNlUFBVRkZIYzF5U083bEFZbnBqaGFtUGswCktxd0xraThxbXQwV2tpK25JcEY5
            TVdUbU0xandOVXpHbWk5WFRvb1VnUUEKLS0tIFlCemZoQzZjbDAwVFFPY3lzdmtx
            a3BXME9sNi9wZWtpQ2RQQStZOEtEOEkKETQ9o6GyfLAz6KzurX9lpZzZcpvK8RBp
            bKQPG2IV44hBxw0TDGNqQs9r3fNo74RVJSk0oO5e+ZqUGmgFYQ7i8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x08qp6qx2pmm5jhc6658mpwrt88c0mr06dxermvja5dux40fglqmeywhn
    lastmodified: "2026-10-03T11:05:51Z"
    mac: ENC[AES256_GCM,data:gaH8ch/+aUMGbH86FylPMB+UkerTp8PbOXOH8utKOhpj+bcrp0B5UTMO9bYuc8lslKJEdd9avypsGH4bRMi4HZIwq2cfIZNBdhMsQy7TC57XsP7si6CQkwpTgxun8HANKbs/27UqVQVRt3mYpHQK/0bm5rIfFuInTXE21LYB5Mk=,iv:FUE1hLMUM+3txl+KJbffOUaQGf6f+R6ZUDEpEhK6T90=,tag:+WkGk6pJZLu5bMrwDTwltg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
