http:
    middlewares:
        badger:
            plugin:
                badger:
                    disableForwardAuth: ENC[AES256_GCM,data:dARX8Q==,iv:XDGsge2fnJzI739wT+MebI9xgoacvGNVdAzt8BAYchA=,tag:Pa7sveEm1pFi8giZtdk7MQ==,type:bool]
        redirect-to-https:
            redirectScheme:
                scheme: ENC[AES256_GCM,data:9CXImx8=,iv:kjThlrD1M4q2UgYmH6qpd1y+GsMJIWeTjSiHB6d1RvQ=,tag:5SCe7BVLWJYD8xYBStZQ7A==,type:str]
    routers:
        main-app-router-redirect:
            rule: ENC[AES256_GCM,data:47x7XTUj0uc+2b1tkTvGXNKs0Miw7zfcw9Lz,iv:QHv8OrdfjiB3ssjjNmZ6EPyyq3de1IHUJ5jaQ1v4Clg=,tag:0pfd45HVnj0gmV9jx2Pz+Q==,type:str]
            service: ENC[AES256_GCM,data:8lF0tjgsXB3z/AFi,iv:Hh7k5kLh/o2tuqiMauFQpoUCYfMdtNcvsp99nvg/Cco=,tag:iPe1jB1/EAQtNZYRc8S5zQ==,type:str]
            entryPoints:
                - ENC[AES256_GCM,data:6M/N,iv:46reneh57G6Svp0QPrsT10zKOiVaTG/NKdpa5aAnoVI=,tag:PO1e5OUWsirQ2WBa+Xv1tw==,type:str]
            middlewares:
                - ENC[AES256_GCM,data:ybjAwHz6QsETmQIYHNOVTs8=,iv:b8y43s9flI/wmwEsX7Wkaou1JbyA3IzavZWXdlx2u5Q=,tag:Vu9J56/cvzrULzDxkTc7Uw==,type:str]
                - ENC[AES256_GCM,data:pfSpr2d5,iv:tcAlUoIan28usGHooyAvqTfJh0+QdTW3t+Tlvg34gHw=,tag:i2Oz3Q/5UMOtYlOdydn0ig==,type:str]
        next-router:
            rule: ENC[AES256_GCM,data:fzObQwe9bxz5sRbUNQAGpk5Av4LvsIfSJT+IbEuQz29n5XIJo3jQomaieg4isple3A43EPs=,iv:12SBRM7SfHy42WemKt/tr/IzYEGf1MtT3BViopOlzL8=,tag:JeuUkVhYL48sNB8pwzYr7A==,type:str]
            service: ENC[AES256_GCM,data:+kp6wDpHMJsR+ECF,iv:vppWe0WPf/tyXaAQuhpUeRMlzQrpLI7eHQDKI9psQI0=,tag:/I5fzGFvk4SVzn3A/0c2Lw==,type:str]
            entryPoints:
                - ENC[AES256_GCM,data:67dhQrNpXB54,iv:ZaHtS6X3CBzCaQ9RPX6BwPQvBhCRY+icIBCp96lkltc=,tag:fJdoPKTtnop3mU8Y5GVeyA==,type:str]
            middlewares:
                - ENC[AES256_GCM,data:+n7MYdoQ,iv:Q1tfa2Ewt5KWxei2Av/4MJg7CDfhD/KuEhJnF+I8NKk=,tag:OBfIhml+i6T7ZUUWcKTlSg==,type:str]
            tls:
                certResolver: ENC[AES256_GCM,data:ISVAw9JS+GQRD4c=,iv:2QqWP0CryYOrvDubk4/f2GR4v7VNPX/i8pWdlCQ35wM=,tag:1VIWmvVykHyW9R8z2UStEA==,type:str]
        api-router:
            rule: ENC[AES256_GCM,data:gP2D2Q3khk5+xnY6MTib8zleGJCtxBAaXXQBmLfn+1kai8rRrmkcHkDBTaINCUk87yN4fw==,iv:mqIuLsWil64DztqD+v1RZypsjMcDjaWjBhdcQdB4nrQ=,tag:lPRspXxchT59LZ/abXZJcQ==,type:str]
            service: ENC[AES256_GCM,data:6cqXxYh+hkjGrao=,iv:kXPljZT7jFGdCMzsciiFgSb5nDBd9Z22vy/SBTmRFqU=,tag:H9H3w225CyzD5UsXnYZeJQ==,type:str]
            entryPoints:
                - ENC[AES256_GCM,data:AH1qP1vIA5wr,iv:ZB18PfYgwsrFK0xSCWC/S3ShEzZoJeDu+lGiXB5S/zs=,tag:Z+8iDw+qVVndkyiUmJzpQA==,type:str]
            middlewares:
                - ENC[AES256_GCM,data:xAa3MOwD,iv:sGx99bIECiBV0T2T8YhyAsF6uYQAE15ujcxSqS0MoUs=,tag:/Am/QgRHiUYLyK/RySfJfw==,type:str]
            tls:
                certResolver: ENC[AES256_GCM,data:D/ivXqV27VQHqBU=,iv:7F/xTtAfs+OLaM9yNlrsOclBmEAUT2uJ6fIRFZradsE=,tag:uB9IsxLXJa+Qjk5f6KIBtQ==,type:str]
        ws-router:
            rule: ENC[AES256_GCM,data:QpL37Q4flseHXSlcbXU2D73geFyH23gMG2v5,iv:6LzVoR0ALu6U5kC9vnI9enXPgcC8lzUhhCbLjyhjWFw=,tag:mQ7DpglExztZBhGnOtTHNQ==,type:str]
            service: ENC[AES256_GCM,data:I+j8nBFyOnRwAcQ=,iv:LrYsJ3vRlW1z6pgYA65MFrrCV4tecn/MgQLKfp7H1WU=,tag:JbpVvWSluhs7NNpXmbt5BQ==,type:str]
            entryPoints:
                - ENC[AES256_GCM,data:UfbWJKwR8VkL,iv:qWHAT9tRBbNBX5rKxAbRD/1Wk1gI4ousJWZs5JofuAs=,tag:n1O1HABY0wZLxIFhExYxjg==,type:str]
            middlewares:
                - ENC[AES256_GCM,data:JV9CnTUB,iv:Y1rLQ1ob6gKupn/lQZSryeOUuVhZg91IYCaeZxT14Pw=,tag:DADjX7blVcafTi8UhqS4RA==,type:str]
            tls:
                certResolver: ENC[AES256_GCM,data:3aC2n5j/BFyYL/U=,iv:jvNqqlEJ4nXYokbwjXUOWcFGjsst6jv8uv66Pj/sxao=,tag:TGRR076kA9O7lLusNpUoew==,type:str]
    services:
        next-service:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:Veh8/RgKC1uWY9XqhITWefW7CP0=,iv:jA1F4EJzLHAWgEit/oXYckBwvSPq5r+IVw/DLsKThWs=,tag:ZxHZlK9aHFot8XGBBZdwCg==,type:str]
        api-service:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:jmBz/VfPHQ1eFS/OIrbIise0CnM=,iv:JXfVG/z0PK0gKFpQK/IfilnXoZ/QblQoLgmz/AhJXGI=,tag:sMUHVQwKegMreids//A9Xw==,type:str]
tcp:
    serversTransports:
        pp-transport-v1:
            proxyProtocol:
                version: ENC[AES256_GCM,data:gQ==,iv:r2hSqwXGoi7jA0F5xxgdd3jmZY1LXRhp6n5HngC2L4o=,tag:gfVjru+NBjpEaU3p9SztNw==,type:int]
        pp-transport-v2:
            proxyProtocol:
                version: ENC[AES256_GCM,data:Hg==,iv:oK8Z4x9vC//UYNNve7OsHmLz6FrFMzI0oVITlp0+TQE=,tag:zJM/8MWu3dJh4JBKelUcQg==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEN2U0tvZyBBckNXYzBJ
            SW5xa3lJKzU2UkxkRm5Nc2ZzdU1XYlB1dWpIQW5rblJCWXM1Swptdkd3aGNEUjVH
            cFovM0VnVWpmeG9PRmtidWU2TkVyb1c2NGg0bWVabzI0Ci0tLSBXNGtONVlTL0RY
            V0xRdDdFcXVSUTVWL1ZMMmFwcUp5U3hKT3J6dkxJa01vChfQUotLeuZKapcG4g9O
            fkxyKiZ7aobsHWPiAOdrgQRlPsAwVknbK0H3O3lHZXzHKFWug8pjEDnX9KkOluHc
            NZQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qfeuzecefcjwjnyup4699fs6nwnz2tl3ymlaad5pxj9kflhc852r7j9e3sa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ3ViZUI2L3B5V2ZrdDlr
            ZFRodFR5Q2dJRUpqM2JKdWpBSHNpL09QS3pBCkJYbjFxZ2xLdERodHJQSCtXeG50
            aWRpU3U5cVV5Umc4K0pNcEpkbHR5aTQKLS0tIDY3NWVCeGJEMitub2IydnZUUGx2
            cldvUVpqaFNnS043d2tWbEJRSWowZFUKtCWfc6grfDOXGEgKinywMADMHKbnXIZ8
            VfAbZVOTpyrnJv2crvzXfDBXelwUBpLAiZnBzqaTfrc/mwIPmpbVNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x08qp6qx2pmm5jhc6658mpwrt88c0mr06dxermvja5dux40fglqmeywhn
    lastmodified: "2026-10-03T11:04:49Z"
    mac: ENC[AES256_GCM,data:3mKOsB85/WzHVRc5Ks8XYNKy7uuknLA8i5oUu3PZc4fi38dlM0EGiL6uG3tm19ek4Ny0tz2ZgufIMp1W1Ntd5Dq7ezfABY0ZEDDcmJLrhADZLO5Bc6MoBM/g5aPY/4Ct6gAmwCKs3MBTIVzeC8VemVMUlWvJYPsd7aWHrZwsHAc=,iv:0C94zowijH+uvTotLDUBD6ToYaDK+J6Q6p8kvvBxUfY=,tag:gA6jNAffR6fK2sBZp2wzMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
